# generated by fastapi-codegen:
#   filename:  openapi/openapi.yaml
#   timestamp: 2023-12-02T05:41:19+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class SensorInfo(BaseModel):
    deviceId: str = Field(..., title='デバイスID')
    temperature: Optional[float] = Field(None, title='温度')
    humidity: Optional[float] = Field(None, title='湿度')
    co2: Optional[float] = Field(None, title='CO2濃度')
    illumination: Optional[float] = Field(None, title='照度')
    soilTemperature: Optional[float] = Field(None, title='土壌温度')
    soilHumidity: Optional[float] = Field(None, title='土壌湿度')
    ec: Optional[float] = Field(None, title='肥料濃度')
    ph: Optional[float] = Field(None, title='pH濃度')
    passing: Optional[bool] = Field(None, title='通過検知')


class ImageInfo(BaseModel):
    deviceId: str = Field(..., title='デバイスID')


class DatetimeInfo(BaseModel):
    datetime: str = Field(
        ..., example='2023-04-01T05:00:30.001000', title='現在時刻（ISO 8601 拡張形式））'
    )
